### ISSUE TITLE
ServerSide Cache Deletion on Stress Test

### ISSUE THREAD

**Issue by xRagnorokx** [thedirtyfew/dash-extensions#120]
Hi, 

First off thanks for building this addition to dash, its really useful!

I'm wondering if you can shed some light on the logic for cache deletion once the cache threshold has been reached? We currently have a dashboard which stores:

1 x General large data cache ~7MB (shared across sessions, updated daily)
10 x small option & default value caches (shared across sessions)
1 x Filtered large data cache ~1k-7MB (session specific)

On a FileSystemStore cache.

We have set the threshold such that, Threshold = N Users + 11 i.e for 100 Users we have set the Threshold at 111

The site works great with a single session, however upon stress testing for a 100 user 10 second ramp up stress test on JMeter, the error rate is near 25% for any call that relies on the caches. Looking at the errors it seems the caches are returning null objects in this case (particularly accessing the session specific ones seem to throw errors way more often than the shared) so I'm guessing they are getting overwritten between being made and being used. This idea seems to hold some truth as when I increase my cache threshold to 1000 the error rate drops to a few percent (at the cost of a 7GB cache!)

With threshold at 111 I would expect no caches to be deleted with 100 users, but they do seem to! But I'm at a complete loss as to why the caches are deleted, as the one that gets deleted should be the oldest which should no longer be in use. 

Ill note that I'm running this in GUnicorn with debug False with 4 cores and 8 threads on a 12 core machine. I have tried varying the CPU and thread count (no change) and I'm not hitting any memory or drive space limits on the machine. Dependency list is below.

Final note: When running the 100 user stress test starting from a completely empty cache it works absolutely great (<0.5% error rate). However running it a second time when the cache is full I get the 25%+ error rate. I would say perhaps the deletion doesn't happen fast enough causing cache creation to fail, but the cache creation steps themselves never seem to fail, only the callbacks which use them... I'm stumped!

Dependencies:
name: dash_run_environment
channels:
  - conda-forge
dependencies:
  - python=3.9.7
  - dash==2.0.0
  - pandas==1.3.4
  - sqlalchemy==1.4.17
  - psycopg2==2.9.2
  - gunicorn==20.1.0
  - pip
  - pip:
    - dash-extensions==0.0.65

Any insights you can provide would be really appreciated! For example is REDIS likely to help with this?

**Comment by emilhe** [comment]
Thanks! As far as I remember, there is no logic on `dash-extensions` with respect to cache deletion. That's the responsibility of the backend. If you use Redis for example, you can configure Redis to delete a cache entry after some time interval (`default_timeout`) has passed. How are you setting up your backend (in code)?

The important thing to note is that you **must** configure the cache so that it **never** ends up clearing elements that are used in an active session. For the default Redis binding for example, I have set the `default_timeout` to 24 hours, as I would expect it to be a reasonable assumption for the user session(s) to be shorter than this.

**Comment by xRagnorokx** [comment]
Thanks for the quick response!

Currently its configured using output_defaults like 

```
        self.server = Flask(__name__)
        self.app = Dash(server=self.server,
                                  output_defaults=dict(backend=FileSystemStore(threshold=112))
        )
```
So its a FileSystemStore Cache for now, not REDIS (yet, that's a plan for the near future im just not sure it will help with this). In the mean time the FileSystemStore is using a threshold limit rather than a timeout and I cant find anything on the Flask-Caching Page I guess thats not really a question for you though!

I guess I have three quick questions otherwise while I have you:

1) Whats the difference between 

            ServersideOutput("store", "data", arg_check=True, session_check=True),
            Input('data-store', 'data')
            
            ServersideOutput("store", "data", arg_check=True, session_check=True),
            Input('data-store', 'data'), memoize=True
                       
I get that memoization saves the last callback output but isn't that what is stored in the serverside output anyway? Yet it seems that the second of these examples creates two cache objects.      

2) What happens if a cache for a session does get deleted while the session in use, I see elsewhere you mention the app dies, does the whole app die completely, needing a full restart? Or just for that user session? Will a simple page refresh fix it? Since there's no way to know if a session has ended (i.e if a user refreshes the page an hour or a day later) how can this ever be stable? Are the sessions determined by cookie? How long does it take for them to expire?

3) Is there anyway of specifying a cache timeout per cache in the Dash Extensions implementation? I see in some of the pure Dash examples this is possible using @cache but all the dash extension examples seem to set it on the initialization of the cache manager rather than per callback. For example I'd like some of my shared caches to never expire, only update. But others can probably go as soon as a session is ended.

**Comment by xRagnorokx** [comment]
Id still appreciate any answers to the above but I think I might have found the issue with the caches being deleted before they are used. Maybe Im mis-reading the Flask-Caching implementation of FileSystemStore but to me it really looks like whenever Flask-Caching hits the threshold value it simply deletes any expired caches + a random 1/3rd of the unsorted cache list...

```
 def _prune(self):
        if self._threshold == 0 or not self._file_count > self._threshold:
            return

        entries = self._list_dir()
        now = time()
        for idx, fname in enumerate(entries):
            try:
                remove = False
                with open(fname, "rb") as f:
                    expires = pickle.load(f)
                remove = (expires != 0 and expires <= now) or idx % 3 == 0

                if remove:
                    os.remove(fname)
            except (IOError, OSError):
                pass
        self._update_count(value=len(self._list_dir()))
```

**Comment by emilhe** [comment]
1) When `memoize=True`, the result will be re-use (the callback code will _not_ be executed on subsequent requests), i.e. the store will act as a cache. Otherwise, the result will be re-calculated every time the callback is triggered.

2) If the cache was cleared for an "active" callback, the return value will be set to `None`,

https://github.com/thedirtyfew/dash-extensions/blob/f59655278eda1ff92ababdb3204953ae08f954e9/dash_extensions/enrich.py#L556

How that affects your app specifically depends on your code, but at least the result will be a degraded user experience. But yes, I believe a page refresh should be enough to get back on track. As you indicate, there is no clear definition of when a session "ends" in Dash. Hence for your setup to be stable, you must to ensure that cache is **only** cleared when the data are no longer needed. What I have typically done for application using `FileSystemCache` is to set no upper limit for cache entries, but run a cron job a 3 AM (that's so far outside work hours so no one will be using the app anyway) that clears the cache folder. 

3) I believe that should be possible if the backend supports timeouts.

**Comment by emilhe** [comment]
Hmm, that implementation looks weird! I get the same impression as you, just looking at the code. If that's how the cache is "cleaned", it makes sense, why you are seeing errors.

**Comment by xRagnorokx** [comment]
Cool so I should definitely have memoize = True on to use the caches.

If clearing it at 3am works and doesn't need a reset of the server then even though my app is possibly 24/hr usage it also wont be critical if it just needs a page refresh every now and then, when the rare occurrence the cache has been not been used in that whole time but the session is still open. Ill have to test it.

Ill open a bug report for Flask-Caching and see what they say, thanks for the help!
