### ISSUE TITLE
dash-extensions doesn't find Namespace after using cx_freeze

### ISSUE THREAD

**Issue by jafi996** [thedirtyfew/dash-extensions#121]
I use the dash_extensions.javascript function `Namespace` to use js code in my dash application.
It works fine when running in the IDE. After building with cx_freeze the Namespace is not found.
The exact error is: 

> `No match for [myNamespace.mySubNamespace.function_name] in the global window object.`

Similar errors occure when usung the `assign` function and when using dash_transcrypt `module_to_props()`

I am using:
`dash=2.1.0`
`dash_extensions=0.0.67`
`dash_transcrypt=0.0.6`
`dash_leaflet=0.1.18`
`cx_freeze=6.10`

Can someone reproduce this behavior? Is this intentional or is my use case not suited for dash?

**Comment by emilhe** [comment]
From the error message, it looks like the generated javascript is not found. I guess the way `cx_freeze ` runs is a bit different from "normal Python", so dash-extensions would probably need some adjustment to make it work. It's intentional (or at least expected) in the sense that no effort has been made to make it work.

**Comment by jafi996** [comment]
Thank you for the feedback. I have tried to make this work for the last couple of weeks but I don't know any more workarounds. I would need your support in looking into the issue and adapting the dash_extension code.

**Comment by emilhe** [comment]
Closed due to inactivity.
