### ISSUE TITLE
[PrefixIdTransform][0.1.0] Multipage design pattern with PrefixIdTransform.

### ISSUE THREAD

**Issue by vmatos** [thedirtyfew/dash-extensions#162]
I am in the process of upgrading some of my Dash apps from `dash-extensions==0.0.71` to the latest `0.1.0`.

When trying to adopt the pattern of achieving a multi-page app by dropping the usage of `dash-extensions.multipage` and use instead the usual https://dash.plotly.com/urls, plus the `DashBlueprint` based pages, embedded in a `DashProxy`.

For reuse of a page, I try to make use of the `PrefixIdTransform` to avoid collisions between component names.

You can find a minimal example here: https://github.com/vmatos/minimal_multipage_prefix

The issue I am having, is that the component ids of the callbacks get the prefix, but the ids in the layout do not. Therefore nothing works.

**Comment by emilhe** [comment]
Did you try out the `pages` module? I dropped the `multipage` because this plugin serves more-or-less the same purpose, and it seems like it will soon be officially supported. With regard to the actual issue, you should use the `_layout_value` when registering the blueprint as a page,

https://github.com/thedirtyfew/dash-extensions/blob/5e250467f372c0f3e48327f293b11ebe58af47cb/dash_extensions/enrich.py#L170

**Comment by vmatos** [comment]
Thank you @emilhe 

I did try the `pages` module as mentioned in the guide: https://www.dash-extensions.com/getting-started/enrich#a-pages. Both from `dash-labs` and from the `dash` 2.4.0rc3. 

However, It seems that the `pages` approach is not compatible with what I want to do:

1. Use `werkzeug.middleware.dispatcher.DispatcherMiddleware`, dispatching paths to different Dash dashboards.
    *  `pages` seems to have troubles importing Dash apps as modules.
    *  Dash page registry/path registry for multipages is global, and does not take into account the "request_prefix_path".
2. Each Dash dashboards could have multiple pages.

After some investigation, it seems `pages` is not compatible with what I am doing: https://github.com/plotly/dash-labs/issues/91.

So I'm using the usual multipage method, as described here: [Multi-page Apps and URL Support](https://dash.plotly.com/urls), and `dash_extensions.enrich.DashBlueprint` + `dash_extensions.enrich.PrefixIdTransform` by following the reference from: https://www.dash-extensions.com/getting-started/enrich#a-embedding.

Indeed calling `DashBlueprint._layout_value()` instead of `DashBlueprint.layout()` solves the issue: https://github.com/vmatos/minimal_multipage_prefix/blob/5c9ac4a86aa83d60d2de7566d4cbc747080e824f/app.py#L60

It was simply my expectation that calling `DashBlueprint.layout()` would have applied the prefix transform to the layout components.

**Comment by emilhe** [comment]
Ah, I am sorry to hear that. I decided to switch to the more official multipage approach of `pages` to get better support for complex uses case, not worse. Let's hope that it will become better with time.

I am happy to know that you got it working. Initially, my intention was that the `layout` property represent the "raw" layout without any transforms applied. But I can see that it's a bit confusing that you need to call the `_layout_value()` function to get the layout to embed (which also means that I have a bug in the documentation). Hence I should probably change the interface slightly so that there is a non-private function with a meaningful name that yields the value of _layout_value().

**Comment by emilhe** [comment]
Closed due to inactivity
