### ISSUE TITLE
Breaking changes for callbacks

### ISSUE THREAD

**Issue by Bougeant** [thedirtyfew/dash-extensions#170]
Hi, 

First of all, I would like to say that this package is great and makes Dash so much better, in particular the ServersideOutput.

However, the past two updates (0.1.0 and 0.1.1) have introduced breaking changes for me. Indeed: 
* Update to v0.1.0 breaks the following format for registering callbacks (runtime error): 
    ```@app.callback(outputs=[Output('output', 'figure')], inputs=[Input('input_1', 'value'), Input('input_2', 'value')])```
    ,which must be replaced by 
    ```@app.callback(Output('output', 'figure'), Input('input_1', 'value'), Input('input_2', 'value'))```

* Update to v.0.1.1 breaks vanilla Dash callback inputs and outputs (`from dash.dependencies import Input, Output` must be replaced by `from dash_extensions.enrich import Input, Output`) so we are forced to use the dash-extensions callback inputs and outputs.

It would be awesome if such breaking changes could be prevented by increased unit test coverage or if a clear indication that named arguments and vanilla callbacks inputs and outputs are no longer supported was provided.

**Comment by emilhe** [comment]
* This flexible callback syntax in not (yet) supported by `dash-extensions`. If it worked with a previous version that has been more by accident than by design
* I have actually been thinking of whether to make it a requirement to import `Input` and `Output` from `dash-extensions`, but I haven't done it yet. At least not intentionally. Could you post a MWE that demonstrates the change in behaviour?

To elaborate a bit on the last point, I have been thinking about whether to use objects for specific transforms (e.g. like the `ServersideOutput`) or simply keywords (like the `break_cycle` keyword introduced in 0.1.1). The latter solution would require all imports to be from `dash-extensions` (which is a minor drawback I guess), while the former means more imports (e.g. an `Output`, `ServersideOutput`, `Input`, and `CyckleBreakingInput` as compared to just `Output` and `Input`).

**Comment by Bougeant** [comment]
Hi Emil, 

Thanks for getting back to me so quickly. And again, I'm very impressed by your contributions to Dash!

Here's a minimal reproducible example that demonstrates the change in behavior:

```
import datetime

from dash import dcc, html
from dash.dependencies import Input as DashInput
from dash.dependencies import Output as DashOutput
from dash_extensions.enrich import (
    DashProxy,
    Input,
    Output,
    ServersideOutput,
)

app = DashProxy()
app.layout = html.Div(
    [
        html.Div(id="value"),
        html.Button("Refresh", id="manual_refresh"),
        dcc.Store(id="store", storage_type="local"),
    ]
)

@app.callback(
    ServersideOutput(component_id="store", component_property="data"),
    Input(component_id="manual_refresh", component_property="n_clicks"),
)
def get_time(n):
    return datetime.datetime.now()

@app.callback(
    DashOutput(component_id="value", component_property="children"),
    DashInput(component_id="store", component_property="data"),
)
def display_time(value):
    return value

app.run_server(host="0.0.0.0", debug=True, port=5000)
```

This app works with v0.1.0, but not with v0.1.1 (unless I replace DashInput by Input) . Here's the error message I get: 
```
"[...]/dash_extensions/enrich.py", line 84, in _collect_args
    raise ValueError(msg)
ValueError: Callback blueprint received an unsupported argument: store.data
```

**Comment by emilhe** [comment]
Ah, yes. Thanks for the example! I can see what is wrong. It is indeed an introduced bug, and it is due to the change in structure required to support keywords for the `Input` component. This seems like another hint that I should have stayed with the other structure, i.e. making a `CycleBreakerInput` object instead. I'll make that change in the next release. Also, to ensure a similar issues doesn't happen again, I have added a unit test that check for this particular compatibility.

BTW: Are you using flexible callbacks extensively?

**Comment by emilhe** [comment]
@Bougeant could you check if `dash-extensions 0.1.2rc2` solves all of your issues?

**Comment by Bougeant** [comment]
Thanks Emil, it does work now!

To be honest, I'm not particularly attached to a specific format for callbacks. It's just that lots of users transitioning from Dash might face the same issues.

**Comment by emilhe** [comment]
@Bougeant thanks for the test! My intention is to minimise the amount of changes required to migrate to use `dash_extensions.enrich`. Hence I would like support all standard Dash syntax to the extent possible - and from 0.1.2 that includes flexible callback signatures :)
