### ISSUE TITLE
Monitor API

### ISSUE THREAD

**Issue by sdementen** [thedirtyfew/dash-extensions#32]
hello @emilhe 

Great to see you new extension Monitor to solve the issue of having the same Component in Input&Output.
However, I am wondering if we could not have a simpler API like the following (with all needed reactjs managed behind the screen)
```python
import dash_core_components as dcc
import dash_html_components as html
from dash import Dash, no_update
from dash.dependencies import Input, Output
from dash_extensions import Monitor

app = Dash()
app.layout = html.Div(
    [
        dcc.Input(id="deg-fahrenheit", autoComplete="off", type="number"),
        dcc.Input(id="deg-celsius", autoComplete="off", type="number"),
    ]
)


@app.callback(
    [Output("deg-fahrenheit", "value"), Output("deg-celsius", "value")],
    [Monitor([Input("deg-fahrenheit", "value"), Input("deg-celsius", "value")])],
)
def sync_inputs(data):
    deg_fahr, deg_cels = data

    # Do the appropriate update.
    if deg_fahr is not None:
        return no_update, (deg_fahr - 32) * 5 / 9
    elif deg_cels is not None:
        return deg_cels * 9 / 5 + 32, no_update


if __name__ == "__main__":
    app.run_server(debug=False)
```
or even simpler with a "*" before the component_id that would do what is needed to avoid the "cannot have the same Input and Output" error message (hoping that some day the special case of having the same Input and Output would work natively in Dash)
```
import dash_core_components as dcc
import dash_html_components as html
from dash import Dash, no_update
from dash.dependencies import Input, Output

app = Dash()
app.layout = html.Div(
    [
        dcc.Input(id="deg-fahrenheit", autoComplete="off", type="number"),
        dcc.Input(id="deg-celsius", autoComplete="off", type="number"),
    ]
)


@app.callback(
    [Output("deg-fahrenheit", "value"), Output("deg-celsius", "value")],
    [Input("deg-fahrenheit", "*value"), Input("deg-celsius", "*value")],
)
def sync_inputs(deg_fahr, deg_cels):
    # Do the appropriate update.
    if deg_fahr is not None:
        return no_update, (deg_fahr - 32) * 5 / 9
    elif deg_cels is not None:
        return deg_cels * 9 / 5 + 32, no_update


if __name__ == "__main__":
    app.run_server(debug=False)
```

This would cover maybe more cases than what Monitor is currently covering (not sure) with a simpler API

**Comment by emilhe** [comment]
In the current implementation of the `Monitor` component, the state is monitored by iterating the children of the `Monitor` component recursively. I suspect this will become a performance issue if there are many components in the tree below the `Monitor` object, but since you place the `Monitor` object yourself, it will be the responsibility of the user to place it "deep enough" in the layout tree.

 To achieve the syntax that you are indicating (without explicitly placing the `Monitor` component), i guess we would have to iterate _all_ components of the app, starting from the top level? While this would work for small apps, i am pretty sure it would become a performance issue at some point. I am not sure how to implement this syntax in a performant way apart from modifying the dash-renderer itself. Do you have any ideas? :)

**Comment by sdementen** [comment]
Can we have a proxy for a given property so that the same property can have two different names (so dash does not complain) which are in fact pointing to the same property?
The we could just wrap any component with this Proxy. Something like Proxy(component, aliased_property="value") and then the proxied object would have both "value" and "value_alias" that are the same property but different names (one can be used as Input and the other as Output). Or have the Proxy who get the id of its child with _alias after and then we can use id_alias.value and id.value as two different component properties which are again referring to the same value

**Comment by emilhe** [comment]
I think this issue has become less relevant, now that the circular callback feature has been added,

https://dash.plotly.com/advanced-callbacks

I will therefore close this issue for now.
