### ISSUE TITLE
MATCH wildcard in MultiplexerTransform

### ISSUE THREAD

**Issue by mortepau** [thedirtyfew/dash-extensions#62]
Would it be possible to support MATCH wildcards where multiple callbacks have the same output?
Currently it errors and gives an error similar to this:

```
TypeError: dict id values must be strings, numbers or bools,
found {'name': 'div', 'id': <MATCH>} in id {'id': { 'name': 'div', 'id': <MATCH> } 'prop': 'children', 'idx': 0}
```

MWE:
```python
from dash_extensions.enrich import DashProxy, MultiplexerTransform, Input, Output, MATCH
import dash_html_components as html

app = DashProxy(transforms=[MultiplexerTransform()])

app.layout = html.Div([
  html.Button("Button 1", id={'type': 'button', 'id': 0}),
  html.Button("Button 1", id={'type': 'button', 'id': 1}),
  html.Div(id={'type': 'div', 'id': 0}),
  html.Div(id={'type': 'div', 'id': 1}),
])

@app.callback(
  Output({'type': 'div', 'id': MATCH}, 'children'),
  Input({'type': 'button', 'id': MATCH}, 'n_clicks'),
)
def cb1(n):
  return "Hello from callback 1"

@app.callback(
  Output({'type': 'div', 'id': MATCH}, 'children'),
  Input({'type': 'button', 'id': MATCH}, 'n_clicks'),
)
def cb2(n):
  return "Hello from callback 2"

if __name__ == '__main__':
  app.run_server(port=7777)

```

**Comment by emilhe** [comment]
I am trying to wrap my head around if this is possible or not. What if you make multiple callbacks, each with MATCH and/or ALL. Then the resulting callback would need to have multiple MATCH and ALL in both input and output. I don't think this is supported in Dash? If you have any conceptual ideas for the implementation and/or any resources suggesting otherwise, please let me know :)

**Comment by mortepau** [comment]
Currently, I don't have any ideas on how to do this...
As a side note, would it be possible to add a note on this limitation in the README until this is resolved or if we see that it can't be solved?

**Comment by emilhe** [comment]
Yes, I plan to update the readme with the next update, which brings clientside callback support and customizable proxy component wrapping.

**Comment by emilhe** [comment]
After looking a bit more into dash pattern matching callbacks, my (preliminary?) conclusion is that the MATCH and ALLSMALLER wildcard would require the presence of one multiplexer proxy component for each MATCH output. And since the latter is dynamic (that's kind of the point), I don't think it is possible to handle this case in the multiplexer. Instead, I have added a more clear error message and a disclaimer in the documentation.

For the ALL wildcard on the other hand, I have made an implementation. You can see my demo example here,

```
from dash_extensions.enrich import DashProxy, MultiplexerTransform, Input, Output, ALL
import dash_html_components as html


def make_callback(i):
    @app.callback(Output({'type': 'div', 'id': ALL}, 'children'), Input({'type': f'button{i}', 'id': ALL}, 'n_clicks'))
    def func(n):
        return [f"Hello from group {i}"] * len(n)


def make_block(i):
    layout = [
        html.Button(f"Button 0 in group {i}", id={'type': f'button{i}', 'id': 0}),
        html.Button(f"Button 1 in group {i}", id={'type': f'button{i}', 'id': 1}),
        html.Div(f"Div {i}", id={'type': f'div', 'id': i}),
    ]
    make_callback(i)
    return layout


app = DashProxy(transforms=[MultiplexerTransform()], prevent_initial_callbacks=True)
app.layout = html.Div(make_block(0) + make_block(1))

if __name__ == '__main__':
    app.run_server(port=7778, debug=True)

```

It should work with the latest (0.0.52) release. If it doesn't please reopen this issue :)

**Comment by Parker-Bergen** [comment]
I would love to have this available for my current situation after a bit of thinking I might have a solution, but I also might not. I just want to state my idea incase it works or even churns out a different way to solve this issue.

IDEA:
Could you not create a store for each match component with an id={type="multiplexer_match_id", index="index of store"} and then utilize the ALL and type in id to say if any of those change then output to the output we want?

I could be way over my head on this one. Please let me know!

**Comment by Parker-Bergen** [comment]
I have linked an example of how I build this idea and it works as intended for my project, however I would much rather use the Multiplexer Transform with Match. I generate stores which then are all listened to for a change, if a change is made then it will write to the one output we need. I just change the index of the store to act as our proxy. Then the last store in the list is used as a previous state holder so we can tell which store has changed since we are listening to all of them for a change.
[Websocket MULTIPLEXER Example.txt](https://github.com/thedirtyfew/dash-extensions/files/8605503/Websocket.MULTIPLEXER.Example.txt)

**Comment by emilhe** [comment]
Is it correctly understood that in your IDEA, you would want to maintain a dynamic number of `Store` components during the app lifetime, i.e. add/remove `Store` components while the app is running?

**Comment by Parker-Bergen** [comment]
Correct. Currently it is manually adjustable however, as more output proxies (in my case, websocket sends outputs) need to be made, then the list would increase allowing for more proxies. In a more dynamic settings it would be better to have a specific previous state specific store, and then stores that expand as more outputs are added.
